### ISSUE TITLE
LaTeX color inconsistency

### ISSUE THREAD

**Issue by newton108** [akamud/vscode-theme-onedark#129]
Colour inside math mode is different.

## Sample code

```
\documentclass[12pt]{article}
\begin{document}

\(x=1\)
\[
    1 + 1 = 2
\]
\begin{equation}
    1 + 2 = 3
\end{equation}
\end{document}
```

## Filename and Language selected
LaTeX `.tex` file,

## Atom Original theme Screenshot

<img width="473" alt="Screenshot 2020-08-31 at 16 13 57" src="https://user-images.githubusercontent.com/3450659/91729541-012bcb80-eba5-11ea-80af-2289d442ab17.png">

## VSCode theme Screenshot

<img width="423" alt="Screenshot 2020-08-31 at 16 16 57" src="https://user-images.githubusercontent.com/3450659/91729830-697aad00-eba5-11ea-85fd-456c4b2a87dc.png">

## Versions used

* VSCode version: 1.48.2
* Theme version: 2.2.2

## Extra information
The only other extension I use is:
LaTeX-Workshop 8.11.1
https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop

**Comment by akamud** [comment]
Hi, thanks for opening this issue.

LaTeX support is only available through plugins, which I don't plan on officially supporting at the moment due to time constraints.

You can customize the theme for your VSCode, though, as explained [here](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme). In order to get the same behavior as the Atom you can just add these customizations:

```json
  "editor.tokenColorCustomizations": {
    "[Atom One Dark]": {
      "textMateRules": [
        {
          "scope": [
            "support.class.math.latex",
            "constant.numeric.math.tex",
            "support.class.math.block.environment.latex"
          ],
          "settings": {
            "foreground": "#98C379",
          }
        }
      ],
    },
  }
```

You should get the same coloring as Atom:
![image](https://user-images.githubusercontent.com/954102/91732379-8bad0480-eb7e-11ea-97cb-0fa488d8e550.png)
