### ISSUE TITLE
Python comments hard to see in git changes

### ISSUE THREAD

**Issue by MadSpindel** [akamud/vscode-theme-onedark#2]
![git-changes](https://cloud.githubusercontent.com/assets/3159565/11451942/aa29eed0-95d6-11e5-8825-73965a7f0f05.PNG)
When you are comparing git changes it is really hard to see Python comments (they are gray).

Should be another color, maybe white?

**Comment by akamud** [comment]
Thanks for the feedback, I'll see if Code makes it possible to change the color in the diff view.

**Comment by akamud** [comment]
Hi @MadSpindel, unfortunately there is no way to change the coloring just in the diff panel.

Atom doesn't have a diff panel like that either, that's why they use this color.

I'll get back to this if we get support for different coloring in the diff panel, but I hardly doubt it will happen as Code uses TextMate colors.

**Comment by akamud** [comment]
This should be better now in version 2.0.0 with better VSCode support. Please let me know if you find anything unusual.
