### ISSUE TITLE
typescript/typescriptReact default keyword inconsistency

### ISSUE THREAD

**Issue by wilomgfx** [akamud/vscode-theme-onedark#45]
**Please provide as much information as possible, usually I need these information to actually start working on an issue, so try to fill as much of these as possible**

## Sample code

none

## Filename and Language selected

``` .ts ``` and ``` .tsx```

## Javascripts normal default keyword

![image](https://d3uepj124s5rcx.cloudfront.net/items/2c0C063j2T3e363U3u01/Image%202017-02-21%20at%2015.45.57.png?v=bc18774a)

Also, wondering why the export and import, from keywords are not purple in ```.js``` files ? 

## VSCode theme Screenshot

![image](https://d3uepj124s5rcx.cloudfront.net/items/3C1U382Q2S3l0R2k2J1N/Image%202017-02-21%20at%2015.39.27.png?v=6aa39808)

## Versions used

* VSCode version: latest
* Theme version: latest

## Extra information

I am using the Javascript(Babel) language mode (when using ```.js```, which might be the reason why im getting weird colors for : export, import, from)

https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring
and
https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode

**Comment by akamud** [comment]
Hi, indeed your assumption is correct, this is not working because you are using a plugin. I don't plan on supporting theming over plugins that need too much customization, or the breaks existing support.

The keywords you mentioned shows correctly without any plugins:

![image](https://cloud.githubusercontent.com/assets/954102/24336264/51ac068a-1262-11e7-8eb0-6e7e9ea242ba.png)

So I'm marking this as `won't fix`.

Thanks for your contribution and please report if you find bugs.

**Comment by wilomgfx** [comment]
No prob, that's what i thought :)!
