### ISSUE TITLE
Add support for Italic attributes in atom-one light/dark theme

### ISSUE THREAD

**Issue by vkbansal** [akamud/vscode-theme-onedark#61]
Continuing from https://twitter.com/_vkbansal/status/872147682084745216

 Is it possible to add support for Italic attributes in atom-one light/dark theme similar to this?

![68747470733a2f2f63646e2d696d616765732d312e6d656469756d2e636f6d2f6d61782f313630302f312a766a70755f6a6f7a52676a56746d7833437470704b412e706e67](https://user-images.githubusercontent.com/5930351/26887228-0f363d10-4bc5-11e7-91b2-8f75780a0710.png)

**Comment by vkbansal** [comment]
Just for reference
https://gist.github.com/brandondurham/3828ac42766f9f187c8e

**Comment by akamud** [comment]
Are you using any plugins to achieve this result?

**Comment by vkbansal** [comment]
Nope. The Gist mentions the hack.

**Comment by akamud** [comment]
I see. I'm planning on keeping this as close to Atom as possible, since there is no way to provide an option for the user to enable or disable this italic behavior, I will not implement this at the moment.

If you don't think there a similar hack to VSCode, you can always fork this repo, it is MIT Licensed.

Thanks for opening the issue and giving more details.

**Comment by vkbansal** [comment]
This theme implements italic fonts and it also has four themes in one package. May be you can combine you light and dark themes in single package
https://github.com/equinusocio/vsc-material-theme

**Comment by akamud** [comment]
I intentionally don't package them together at the moment. Maybe I'll create a new package that bundles them in the future.

As for the italic, I don't plan on adding this to the theme at the moment, simply because it is not something available in the Atom official theme.
