### ISSUE TITLE
What about the font

### ISSUE THREAD

**Issue by ArinGAMER** [akamud/vscode-theme-onedark#78]
its easy to do it ourself but you should add it or at least put it in readme  so everyone can easily do it

**Comment by akamud** [comment]
Hi, thanks for your feedback.

My main motto with this port is to keep it as close as possible to Atom's original theme, which doesn`t customize the font.

But you are right, adding this to the README might be a good option since so many people are asking for it. The next version will come with this information.

Thank you!
