### ISSUE TITLE
URL color is not the original

### ISSUE THREAD

**Issue by superlativo77** [akamud/vscode-theme-onedark#90]
I love it this color theme. I am an old Atom user. The URL original color is #56B6C2

Great work!

**Comment by akamud** [comment]
Hi @superlativo77, thanks for submitting this. This issue with URLs [has come up before](https://github.com/akamud/vscode-theme-onedark/issues/64#issuecomment-331655870), unfortunately, VSCode doesn't support URLs customization per language, so all I have is a global scope, and choosing a green color is the less disruptive option. Choosing a cyan color feels weird in other scenarios, so I chose green because URLs usually come inside strings, which are green too.

This has been discussed [here](https://github.com/Microsoft/vscode/issues/18378) in VSCode.

I'll close this since it is not supported at the moment.
